import axiosInstance from './axiosInstance';
import type { AudioReference, AudioReferencesResponse } from './types';

// Type for audio data when creating a new audio reference, omitting fields generated by the backend.
// Assuming 'createdAt' and 'updatedAt' are backend-generated, like 'id'.
type CreateAudioReferenceData = Omit<AudioReference, 'id' | 'createdAt' | 'updatedAt'>;

export const fetchAudioReferences = async (): Promise<AudioReferencesResponse> => {
  const response = await axiosInstance.get<AudioReferencesResponse>('/audio');
  return response.data;
};

export const fetchAudioReferencesByBookId = async (
  bookId: number
): Promise<AudioReferencesResponse> => {
  const response = await axiosInstance.get<AudioReferencesResponse>(`/audio/book/${bookId}`);
  return response.data;
};

export const fetchAudioReferenceById = async (id: number): Promise<AudioReference> => {
  const response = await axiosInstance.get<AudioReference>(`/audio/${id}`);
  return response.data;
};

export const createAudioReference = async (
  audioData: CreateAudioReferenceData
): Promise<AudioReference> => {
  const response = await axiosInstance.post<AudioReference>('/audio/add', audioData);
  return response.data;
};

export const updateAudioReference = async (
  id: number,
  audioData: Partial<AudioReference>
): Promise<AudioReference> => {
  const response = await axiosInstance.put<AudioReference>(`/audio/${id}`, audioData);
  return response.data;
};

export const deleteAudioReference = async (id: number): Promise<void> => {
  await axiosInstance.delete(`/audio/${id}`);
};
