import axiosInstance from './axiosInstance';
import type { Book, BooksResponse } from './types';

// Type for book data when creating a new book, omitting fields generated by the backend
// Assuming 'createdAt' and 'updatedAt' are also backend-generated, similar to 'id'.
// If not, they should be removed from this Omit type.
type CreateBookData = Omit<Book, 'id' | 'createdAt' | 'updatedAt'>;

export const fetchBooks = async (): Promise<BooksResponse> => {
  const response = await axiosInstance.get<BooksResponse>('/books');
  return response.data;
};

export const fetchBookById = async (id: number): Promise<Book> => {
  const response = await axiosInstance.get<Book>(`/books/${id}`);
  return response.data;
};

export const createBook = async (bookData: CreateBookData): Promise<Book> => {
  const response = await axiosInstance.post<Book>('/books/add', bookData);
  return response.data;
};

export const updateBook = async (id: number, bookData: Partial<Book>): Promise<Book> => {
  const response = await axiosInstance.put<Book>(`/books/${id}`, bookData);
  return response.data;
};

export const deleteBook = async (id: number): Promise<void> => {
  await axiosInstance.delete(`/books/${id}`);
};
