import axiosInstance from './axiosInstance';
import { VideoReference, VideoReferencesResponse } from './types';

// Type for video data when creating a new video reference, omitting fields generated by the backend.
type CreateVideoReferenceData = Omit<VideoReference, 'id' | 'createdAt' | 'updatedAt'>;

export const fetchAllVideoReferences = async (): Promise<VideoReferencesResponse> => {
  const response = await axiosInstance.get<VideoReferencesResponse>('/video');
  return response.data;
};

export const fetchVideoReferencesByBookId = async (bookId: number): Promise<VideoReferencesResponse> => {
  const response = await axiosInstance.get<VideoReferencesResponse>(`/video/book/${bookId}`);
  return response.data;
};

export const fetchVideoReferenceById = async (id: number): Promise<VideoReference> => {
  const response = await axiosInstance.get<VideoReference>(`/video/${id}`);
  return response.data;
};

export const createVideoReference = async (videoData: CreateVideoReferenceData): Promise<VideoReference> => {
  // Note: Original app used POST /video, not /video/add
  const response = await axiosInstance.post<VideoReference>('/video', videoData);
  return response.data;
};

export const updateVideoReference = async (id: number, videoData: Partial<VideoReference>): Promise<VideoReference> => {
  const response = await axiosInstance.put<VideoReference>(`/video/${id}`, videoData);
  return response.data;
};

export const deleteVideoReference = async (id: number): Promise<void> => {
  await axiosInstance.delete(`/video/${id}`);
};

export const searchVideoReferences = async (query: string): Promise<VideoReferencesResponse> => {
  const response = await axiosInstance.get<VideoReferencesResponse>('/video/search', {
    params: { query },
  });
  return response.data;
};
