import React, { useState, useEffect } from 'react';
import { AudioReference } from '../../api/types';

// Type for form data, omitting fields generated by the backend or not directly edited in this form
type AudioFormData = Omit<AudioReference, 'id' | 'createdAt' | 'updatedAt'>;

interface AudioFormProps {
  initialData?: Partial<AudioReference>; // Make initialData fully optional
  onSubmit: (formData: AudioFormData) => void;
  isSaving?: boolean;
  submitButtonText?: string;
}

const AudioForm: React.FC<AudioFormProps> = ({
  initialData = {}, // Default to empty object if undefined
  onSubmit,
  isSaving = false,
  submitButtonText = 'Save Audio Reference',
}) => {
  const [formData, setFormData] = useState<AudioFormData>({
    title: initialData.title || '',
    bookId: initialData.bookId || undefined, // Or some default if appropriate
    url: initialData.url || '',
    description: initialData.description || '',
    duration: initialData.duration || undefined,
    speaker: initialData.speaker || '',
    language: initialData.language || 'English',
    // Ensure all fields in AudioFormData are initialized
    // Add any other fields that might be part of AudioFormData but not in initialData typically
  });

  useEffect(() => {
    // Update form if initialData changes and is provided
    // This handles cases where the form might be re-used or initialData loads asynchronously
    if (initialData && Object.keys(initialData).length > 0) {
      setFormData({
        title: initialData.title || '',
        bookId: initialData.bookId || undefined,
        url: initialData.url || '',
        description: initialData.description || '',
        duration: initialData.duration || undefined,
        speaker: initialData.speaker || '',
        language: initialData.language || 'English',
        // Map other fields as necessary
      });
    }
  }, [initialData]);

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: (name === 'bookId' || name === 'duration') ? (value === '' ? undefined : Number(value)) : value,
    }));
  };

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    onSubmit(formData);
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6 p-4 bg-white shadow-md rounded-lg">
      <div>
        <label htmlFor="title" className="block text-sm font-medium text-gray-700">
          Title <span className="text-red-500">*</span>
        </label>
        <input
          type="text"
          name="title"
          id="title"
          value={formData.title}
          onChange={handleChange}
          required
          className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
        />
      </div>

      <div>
        <label htmlFor="bookId" className="block text-sm font-medium text-gray-700">
          Book ID
        </label>
        <input
          type="number"
          name="bookId"
          id="bookId"
          value={formData.bookId === undefined ? '' : formData.bookId}
          onChange={handleChange}
          className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
        />
      </div>

      <div>
        <label htmlFor="url" className="block text-sm font-medium text-gray-700">
          Audio URL <span className="text-red-500">*</span>
        </label>
        <input
          type="url"
          name="url"
          id="url"
          value={formData.url}
          onChange={handleChange}
          required
          className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
        />
      </div>

      <div>
        <label htmlFor="description" className="block text-sm font-medium text-gray-700">
          Description
        </label>
        <textarea
          name="description"
          id="description"
          value={formData.description}
          onChange={handleChange}
          rows={3}
          className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
        />
      </div>
      
      <div>
        <label htmlFor="duration" className="block text-sm font-medium text-gray-700">
          Duration (seconds)
        </label>
        <input
          type="number"
          name="duration"
          id="duration"
          value={formData.duration === undefined ? '' : formData.duration}
          onChange={handleChange}
          className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
        />
      </div>

      <div>
        <label htmlFor="speaker" className="block text-sm font-medium text-gray-700">
          Speaker
        </label>
        <input
          type="text"
          name="speaker"
          id="speaker"
          value={formData.speaker}
          onChange={handleChange}
          className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
        />
      </div>

      <div>
        <label htmlFor="language" className="block text-sm font-medium text-gray-700">
          Language
        </label>
        <input
          type="text"
          name="language"
          id="language"
          value={formData.language}
          onChange={handleChange}
          className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
        />
      </div>

      <div>
        <button
          type="submit"
          disabled={isSaving}
          className="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50"
        >
          {isSaving ? 'Saving...' : submitButtonText}
        </button>
      </div>
    </form>
  );
};

export default AudioForm;
